worker:
  limiter:
    enabled: False
    requests_per_second: 500
  wordlists:
    - /home/mat/documents/godirb/config/test.txt
  append: 
    - .html
    - .php
    - .css
    - .js
  ignore: 
    - 403
    - 401
  max_threads: 3
requests:
  cookie: abcdefg
  headers:
  - header: Authorization
    content: Bearer 123
  - header: Content-Type
    content: application/json
logging:
  stats: True
  debug_logger:
    file: ./debug.json
    json_dump: False
    live: False
  success_logger:
    file: ./oks.json
    json_dump: False
    live: True
  error_logger:
    file: ./errors.json
    json_dump: False
    live: False