worker:
  limiter:
    enabled: True
    requests_per_second: 100 
  wordlists:
    - /home/mat/documents/godirb/config/test.txt
  append: 
    - .html
    - .php
    - .css
    - .js
  # ignore: 
  #   - 403
  #   - 401
  max_threads: 10
requests:
  cookie: abcdefg
  headers:
  - header: Authorization
    content: Bearer 123
  - header: Content-Type
    content: application/json
logging:
  stats: True
  debug_logger:
    file: ./debug_logs.json
    json_dump: False
    live: False
  success_logger:
    file: ./oks.json
    json_dump: False
    live: True
  error_logger:
    json_dump: False
    live: False