worker:
  wordlists:
    - /home/mat/documents/godirb/config/test.txt
  append: 
    - .html
    - .php
  ignore: 
    - 403
    - 401
  max_threads: 50
logging:
  enabled: True
  debug: False
requests:
  cookie: abcdefg
  headers:
  - header: Authorization
    content: Bearer 123
  - header: Content-Type
    content: application/json